### ISSUE TITLE
Looking glass breaks Journeymap and Mapwriter minimaps

### ISSUE THREAD

**Issue by Robijnvogel** [XCompWiz/LookingGlass#7] opened 2015-06-06 21:17 UTC
This:
http://i918.photobucket.com/albums/ad25/dgms17/2015-06-06_22.57.37_zpsb30jqvyc.png
Happened after I installed looking glass on my setup and traveled (within the same dimension) using a Mystcraft book.
It seems to remove the non-rectangular boundary "masks" that both Journeymap and Mapwriter use to hide part of their preloaded minimap. (I have Mapwriter installed because it is part of Opis and I actually like to use Journeymap for mapping purposes, in case you were wondering.)
I have traveled using the same Mystcraft books in the same world before, but without looking glass installed. This did not happen back then.

**Comment by SanAndreaP** [comment] 2015-06-07 15:04
This bug not only breaks minimaps, but also any in-world rendering. Therefore rendering this mod currently unusable for me.

I'm smelling a leaking OpenGL state here...

PS: This is what I see after looking at a book:
http://i.imgur.com/WRyTC0D.png

Steps to reproduce:
- Make a Linking book for the Overworld to get back (naturally)
- Make an empty descriptive book
- Travel to this random dimension
- Travel back to the overworld with the linking book
- Look at the generated dimension in the book
- Rendering is meesed up now, making me restart the game

**Comment by XCompWiz** [comment] 2015-06-07 17:12
Does this only happen when you link? Not when you just look at the book and close it without linking?
Does this happen if you try the LookingGlass testing command?

**Comment by Gnomeo** [comment] 2015-06-08 03:22
I observed this twice today.  The visual effect is similar to the original post above.  The first time happened when I placed a linking book in a stand through the gui, closed the book, and did not travel.  The second time I opened the same book from a stand and traveled; the graphical issue happened upon arrival.  Full shutdown of the program required to return graphics to normal.

Not sure if the following helps any, but I also noticed that when I logged out of the world the graphical issue persisted in the main screen.  I'm not sure what mod it is, but my character model appears to the right of the menu on the main screen, and a random (changes each time you view the menu) mob shows up on the left side.  The models look like they're rendered back to front, and clip through themselves.

**Comment by XCompWiz** [comment] 2015-06-08 19:05
Sounds like the depth buffer is getting killed.  I'll see what I can figure out. :)

**Comment by XCompWiz** [comment] 2015-06-08 21:30
OK... Looks like I might already have fixed this...
I just set up a test instance with JourneyMap with my testing world.  No issues at all.  Could not reproduce the effect.
I did do some cleanup the other day, part of which removed some erroneous GL calls (doing things that didn't need to be done), so that might have fixed the issue.
For the record, I am using a version of JourneyMap from April, since that's what I had, and the latest version of Forge.
Not sure when the build will go up. Probably this weekend, maybe sooner. :)

**Comment by Robijnvogel** [comment] 2015-06-09 00:44
@Gnomeo fyi, that main menu mob rendering is done by bspkrsCore

It may be good to notice that I have had graphical glitch problems with iChun's Morph and Divisor's Smart Moving (and/or supporting mods)

**Comment by BarbasTheDog** [comment] 2015-06-22 23:36
I have had the same issue, even though I don't have JourneyMap. I do have Mapwriter though, but the minimap is always disabled when it happens. The only way to fix that I found is to restart the game, going back to the main menu doesn't help.

http://i.imgur.com/BITG8XE.png

**Comment by Otto42** [comment] 2015-06-26 19:48
FTB Direwolf20 1.4.1 pack.

I updated it to Mystcraft 0.11.13 and LookingGlass 0.1.1 and found this same problem. Notably, it didn't happen every time I looked at a book, but travelling was not required. Simply looking at it can cause it to occur.

As a test, I downgraded to Mystcraft 0.11.11 and LookingGlass 0.1.0. No changes, problem still occurs.

**Comment by XCompWiz** [comment] 2015-07-13 20:27
Does this still occur with the most recent version of LookingGlass?

**Comment by Robijnvogel** [comment] 2015-07-28 21:56
With the newest versions of LookingGlass and Mystcraft (and Binnie's Mods) all my attempts to reproduce this issue have been in vain.

You win this time binary mage, but we shall meet again.

**Comment by XCompWiz** [comment] 2015-07-30 18:04
XD Fantastic response. I look forward to our next meeting. :D

**Comment by XCompWiz** [comment] 2015-10-19 14:02
Somehow I never closed this issue, despite it being reported fixed.  _shrugs_

**Closed as completed** 2015-10-19 14:02 UTC
